#!/usr/bin/python
# Author Ahamed Sadayan
# Template for http post leaf ASN policy for BGP fabric
# After import make changes to the relevant field



leaf_asn_policy= {"id":38020,
                  "policyId":"POLICY-38020",
                  "description":"leaf_asn",
                  "serialNumber":"FDO233804NA",
                  "entityType":"SWITCH",
                  "entityName":"SWITCH",
                  "templateName":"leaf_bgp_asn",
                  "templateContentType":"",
                  "nvPairs":{"SERIAL_NUMBER":"",
                             "BGP_AS":"1234560",
                             "PRIORITY":"500",
                             "POLICY_DESC":"leaf_asn",
                             "FABRIC_NAME":"NHN-S1",
                             "POLICY_ID":"POLICY-38020"},
                  "generatedConfig":"",
                  "autoGenerated":None,
                  "deleted":None,
                  "source":"",
                  "priority":500,
                  "status":"NA",
                  "statusOn":'',
                  "createdOn":'',
                  "modifiedOn":''}






