#!/usr/bin/python
# Author Ahamed Sadayan
# Template for http post VRF creation
# After import make changes to the relavent field

vrf = {
        "fabric": "",
        "vrfName": "",
        "enforce": None,
        "defaultSGTag": None,
        "vrfTemplate": "Default_VRF_Universal",
        "vrfExtensionTemplate": "Default_VRF_Extension_Universal",
        "vrfTemplateConfig": {"advertiseDefaultRouteFlag":"true",
                              "routeTargetImport":"",
                              "vrfVlanId":"",
                              "isRPExternal":"false",
                              "vrfDescription":"",
                              "disableRtAuto":"false",
                              "L3VniMcastGroup":"",
                              "maxBgpPaths":"2",
                              "maxIbgpPaths":"2",
                              "vrfSegmentId":"",
                              "routeTargetExport":"",
                              "ipv6LinkLocalFlag":"true",
                              "vrfRouteMap":"FABRIC-RMAP-REDIST-SUBNET",
                              "routeTargetExportMvpn":"", 
                               "ENABLE_NETFLOW":"false", 
                               "configureStaticDefaultRouteFlag":"true", 
                               "tag":"12345", 
                               "rpAddress":"",
                               "trmBGWMSiteEnabled":"false", 
                               "mvpnInterAs":"false", 
                               "nveId":"1", 
                               "enableL3VniNoVlan":"true", 
                               "routeTargetExportEvpn":"", 
                               "NETFLOW_MONITOR":"", 
                               "bgpPasswordKeyType":"", 
                               "bgpPassword":"", 
                               "mtu":"9216", 
                               "multicastGroup":"", 
                               "routeTargetImportMvpn":"", 
                               "isRPAbsent":"false", 
                               "advertiseHostRouteFlag":"false", 
                               "vrfVlanName":"",
                               "trmEnabled":"false", 
                               "loopbackNumber":"", 
                               "asn":"",
                               "vrfIntfDescription":"", 
                               "routeTargetImportEvpn":"", 
                               "vrfName":""},
        "tenantName": None,
        "id": "3",
        "vrfId": "",
        "serviceVrfTemplate": None,
        "source": None,
        "vrfStatus": "NA",
        "hierarchicalKey": ""}
